services:
  postgresql:
    image: postgres:15
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: revenue
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d

volumes:
  pgdata: